# Generated by Django 6.0.1 on 2026-02-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadhistory',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
